apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector: {}
  serviceName: postgres
  replicas: 1
  podManagementPolicy: Parallel
  template:
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - mongo
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgres
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /mnt/data
              name: postgredb
          resources:
            requests:
              cpu: 60m
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database.secret

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username.secret

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password.secret

  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ ReadWriteOnce ]
        storageClassName: fast
        resources:
          requests:
            storage: 20Gi
